receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"

exporters:
    splunk_hec/traces:
        
        # Splunk HTTP Event Collector token.
        token: "4c06387f-b4ef-4207-aaa7-bbe48e71e955"
        
        # URL to a Splunk instance to send data to.
        endpoint: "https://splunk:8088/services/collector"
        
        # Optional Splunk source: https://docs.splunk.com/Splexicon:Source
        source: "otel-collector"
        
        # Optional Splunk source type: https://docs.splunk.com/Splexicon:Sourcetype
        sourcetype: "traces"
        
        # Splunk index, optional name of the Splunk index targeted.
        index: "traces"
        
        # Whether to disable gzip compression over HTTP. Defaults to false.
        disable_compression: false
        # HTTP timeout when sending data. Defaults to 10s.
        timeout: 10s
        log_data_enabled: true
        profiling_data_enabled: true
        
        # Whether to skip checking the certificate of the HEC endpoint when sending data over HTTPS. Defaults to false.
        # For this demo, we use a self-signed certificate on the Splunk docker instance, so this flag is set to true.
        tls:
          insecure_skip_verify: true

extensions:
    health_check:
      endpoint: 0.0.0.0:13133
    pprof:
      endpoint: :1888
    zpages:
      endpoint: :55679
processors:
    batch:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [splunk_hec/traces]
  
  telemetry:
    logs:
      level: "debug"
      development: true
      encoding: "console"
